[package]
name = "beryl_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
beryl_syntax = { workspace = true }
beryl_sema = { path = "../beryl_sema" }
beryl_codegen = { path = "../beryl_codegen" }
thiserror = { workspace = true }
logos = { workspace = true }
chumsky = { workspace = true }