[package]
name = "lency_syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
# 依赖基础设施
lency_diagnostics = { workspace = true }

# 解析工具
logos = { workspace = true }
chumsky = { workspace = true }
lasso = { workspace = true }